version: "3"
services:
  host:
    build:
      args:
        APP: host
    image: pokesummary-host-mfs
    ports:
      - 8000:80
  home:
    build:
      args:
        APP: home
    image: pokesummary-home-mfs
    ports:
      - 8001:80
  pokemons:
    build:
      args:
        APP: pokemons
    image: pokesummary-pokemons-mfs
    ports:
      - 8002:80
  games:
    build:
      args:
        APP: games
    image: pokesummary-games-mfs
    ports:
      - 8003:80
  config-api:
    build: ./api
    image: pokesummary-config-api-mfs
    ports:
      - 3000:80
