version: "3"
services:
  host:
    build:
      args:
        APP: host
    image: pokesummary-host
    ports:
      - 8000:80
  home:
    build:
      args:
        APP: home
    image: pokesummary-home
    ports:
      - 8001:80
  pokemons:
    build:
      args:
        APP: pokemons
    image: pokesummary-pokemons
    ports:
      - 8002:80
  games:
    build:
      args:
        APP: games
    image: pokesummary-games
    ports:
      - 8003:80
